# Generated by Django 6.0 on 2025-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
