# Generated by Django 6.0 on 2025-12-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_alter_journey_description'),
        ('portfolio', '0008_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='portfolio.skill'),
        ),
    ]
