# Generated by Django 6.0 on 2025-12-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g., GitHub, LinkedIn', max_length=50)),
                ('url', models.URLField(help_text='Full URL to your social profile')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about_me.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
