# Generated by Django 6.0 on 2025-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_technologies_projectimage'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='projects', to='services.service'),
        ),
    ]
