# Generated by Django 6.0 on 2025-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_client_rename_url_project_live_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsection',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='projectsection',
            old_name='title',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='projectsection',
            name='is_highlight',
            field=models.BooleanField(default=False, help_text='Use for testimonials, results, or special callouts'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='subheading',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
