# Generated by Django 6.0 on 2025-12-15 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_client_rename_url_project_live_url_and_more'),
        ('testimonials', '0002_testimonial_approved_testimonial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.client'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
