# Generated by Django 6.0 on 2025-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonial_client_testimonial_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
